import type { Metadata } from 'next';
import { inter } from '@/lib/fonts';
import './globals.css';
import AuthProvider from '@/context/AuthProvider';
import Toast from '@/components/UI/toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={`${inter.className} `}>
          <Toast />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
